%YAML:1.0

#common parameters
# savePath: "/home/liuxuwei/Files/mrobot_ws/src/log/4.22/"
savePath: "/home/liuxuwei/Files/"
# savePath: "/home/liuxuwei/Files/mrobot_ws/src/log/little/"
bag_path: "/home/liuxuwei/Files/mrobot_ws/src/log/4.22/2021-04-06-21-12-55.bag"

scan_topic_name: "/scan"
img_topic_name: "/camera/color/image_raw"

# tag info
# tag_type: 1 # 1: kalibr_tag, 2: apriltag
# tag_size: 0.021 # tag size, unit meter
# tag_spacing: 0.0061 # tag spacing, only used in kalibr_tag. For details, please see kalibr tag description.
# black_border: 2 # if you use kalibr_tag black_boarder = 2; if you use apriltag black_boarder = 1

tag_type: 1 # 1: kalibr_tag, 2: apriltag
tag_size:  0.0878 # tag size, unit meter 87.8
# tag_spacing: 0.0262 # tag spacing, only used in kalibr_tag. For details, please see kalibr tag description. 26.2
tag_spacing: 0.3
black_border: 2 # if you use kalibr_tag black_boarder = 2; if you use apriltag black_boarder = 1

# tag_type: 1 # 1: kalibr_tag, 2: apriltag
# tag_size:  0.0234 # tag size, unit meter 87.8
# tag_spacing: 0.3 # tag spacing, only used in kalibr_tag. For details, please see kalibr tag description. 26.2
# black_border: 2 # if you use kalibr_tag black_boarder = 2; if you use apriltag black_boarder = 1

 
#camera calibration 
# model_type: KANNALA_BRANDT
model_type: PINHOLE
camera_name: cam0
image_width: 1280
image_height: 720

distortion_parameters:
   k1: -0.055028777569532394
   k2:   0.0668683722615242
   p1: -0.0004267295589670539
   p2: 0.0004448417166713625

projection_parameters:
   fx: 632.3165283203125 
   fy: 631.891845703125
   cx: 634.24224853
   cy: 368.97882080
